export const FETCH_POSTS_REQUEST: string = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS: string = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE: string = 'FETCH_POSTS_FAILURE';

export const FETCH_COMMENTS_REQUEST: string = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS: string = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE: string = 'FETCH_COMMENTS_FAILURE';

export const ADD_COMMENT: string = 'ADD_COMMENT';